##
# @description Build automatization
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
##
name: Build

on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main

jobs:
  build:
    name: Execute build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install
        id: npm-ci
        run: npm ci

      - name: Lint
        run: npm run refactor

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build